name: Genarate ASCII Artwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
           
        - name: Setup cowsay
          run: |
           sudo apt-get install cowsay -y
           cowsay -f dragon >> dragon.txt
        
        - name: Sleep for 10 sec
          run: sleep 10
          
    
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout
        #   uses: actions/checkout@v4
           
        - name: test file exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job:
        needs: [build_job,test_job]
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout
        #   uses: actions/checkout@v4
           
        - name: test file exists
          run: cat dragon.txt