name: Genarate ASCII Artwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
           
        - name: Setup cowsay
          run: |
           sudo apt-get install cowsay -y
           cowsay -f dragon >> dragon.txt
        
        - name: Upload Dragon txt File
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt
          
    
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon txt File
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        # - name: Checkout
        #   uses: actions/checkout@v4
        - name: test file exists
          run: ls
           
        # - name: test file exists
        #   run: grep -i "dragon" dragon.txt
    
    # deploy_job:
    #     needs: [build_job,test_job]
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Download Dragon txt File
    #       uses: actions/download-artifact@v4
    #       with:
    #         name: dragon-text-file
    #     # - name: Checkout
    #     #   uses: actions/checkout@v4
           
    #     - name: test file exists
    #       run: cat dragon.txt