name: Genarate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
           
        - name: Setup cowsay
          run: |
           sudo apt-get install cowsay -y
           cowsay -f dragon >> dragon.txt
           cat dragon.txt