name: matrixs workflow

on: 
    push:
    workflow_dispatch:

jobs:
  deploy:
    strategy:
     fail-fast: false
    #  max-parallel: 2
     matrix:
        os: [ubuntu-lastest, windows-latest]
        images: [hello-world, alpine]
        exclude:
            - images: alpine
              os: windows-lastest
        include:
            - images: amd64/alpine
              os: ubuntu-lastest

    runs-on: ${{matrix.os}}
    steps:
      - name: echo Docker details
        run: docker info
        
      - name: Rune images on ${{ matrix.os}}
        run: docker run ${{ matrix.images}}
            
            
